theme: jekyll-theme-dinky
title: Alex Shulga
description: Senior Software Engineer @ Tizen Platform Lab, Samsung
owner_resume_url: https://github.com/shulgaalexey/shulgaalexey.github.io/blob/master/docs/AlexShulga_Resume_20170726.docx?raw=true
owner_linkedin_url: https://www.linkedin.com/in/alexey-shulga-a8678443/
stackoverflow_url: https://stackoverflow.com/story/shulgaalexey
