theme: jekyll-theme-dinky
title: Alex Shulga
description: Senior Software Engineer @ Samsung Research Center
owner_resume_url: https://github.com/shulgaalexey/shulgaalexey.github.io/blob/master/docs/AlexShulga_Resume_20180118.docx?raw=true
owner_cover_ltr_url: https://github.com/shulgaalexey/shulgaalexey.github.io/blob/master/docs/AlexShulga_Cover_Ltr_20180118.docx?raw=true
owner_linkedin_url: https://www.linkedin.com/in/alex-shulga/
stackoverflow_url: https://stackoverflow.com/story/shulgaalexey
