theme: jekyll-theme-dinky
title: Alex Shulga
description: Senior Software Engineer @ Tizen Platform Lab, Samsung
owner_resume_url: https://www.dropbox.com/s/r8n38zkjbvcei3z/AlexShulga_Resume_20170726.docx?dl=0
owner_linkedin_url: https://www.linkedin.com/in/alexey-shulga-a8678443/
stackoverflow_url: https://stackoverflow.com/story/shulgaalexey
