theme: jekyll-theme-dinky
title: Alex Shulga
description: Senior Software Engineer @ Tizen Platform Lab, Samsung
owner_resume_url: https://www.dropbox.com/s/lmdwzlm3w1gmcpg/AlexShulga_Resume.docx?dl=0
owner_linkedin_url: https://www.linkedin.com/in/alexey-shulga-a8678443/
